### ISSUE TITLE
Different bg

### ISSUE THREAD

**Issue by dmnfr** [JasonPuglisi/lastfm-now#5]
Hi,

It could be a nice feature to have a different background that the cover already displayed, for exemple an artist picture (with an option ?bg=artist)
For this we could use the artist images provided by spotify API : 
https://api.spotify.com/v1/artists/0oSGxfWSnnOXhD2fKuz2Gy
or 
https://api.spotify.com/v1/search?q=David+Bowie&type=artist&limit=1

-> artists.images[0].url

**Comment by JasonPuglisi** [comment]
Might consider this, but I'm not sure.

In the meantime, I believe someone forked the project and did this at https://github.com/beschoenen/lastfm-now.

**Comment by JasonPuglisi** [comment]
Actually working on this now. I decided to add a separate configuration page that will allow the user to choose album, artist, or none for background. This will also help the user choose weather units since the new OpenWeatherMap implementation doesn't have an automatic mode.

**Comment by JasonPuglisi** [comment]
Well this is done, but I'm not _totally_ happy with the end result. Last.fm's artist images seem to all or mostly be square, and they don't fit very well for backgrounds. In any case, at least now it's possible!

**Comment by JasonPuglisi** [comment]
One last comment. I changed the CSS so that the background image is focused on the top. It looks a bit better now :)
