### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by Andreas-Wotte** [JasonPuglisi/lastfm-now#7]
I presuppose, this isn't the time for new ideas on Last.FM, especially in a situation of a seemingly stagnating development process where the whole world is waiting for tags, groups, bbc, about me, playlists and so on. But for later here my idea: 
You be aware of the <a href=https://wagnaria.xyz/now/>"Play Now" tool by Wagnaria</a>. Ok, so far, so unspectacular. Now imagine, this old Last.FM tool was reinstalled and linked with the recent track list for full screen. And now we go one step further and imagine, instead of a static picture of the currently played track, we see a slideshow of the uploaded artists pictures on fullscreen you just listen to, stopable with f11 or whatever.

**Comment by JasonPuglisi** [comment]
While it's an interesting idea, I think you may be a bit mistaken here. Sadly, this project isn't affiliated with Last.fm, and has nothing to do with the development of their services or website. What you're suggestion could definitely be created as a standalone website/feature, but I don't think it fits with the goal of this project. Last.fm Now is meant to be a simple HUD for currently playing songs. Perhaps an interested developer could create a fork with your suggested functionality. For now though, I'm closing this as I think it would be more of a feature creep.
