### ISSUE TITLE
Fullscreen web app support

### ISSUE THREAD

**Issue by noooz** [JasonPuglisi/lastfm-now#8]
Thanks for your app. I love it to see a replacement for last.fm's missing now playing site.

What about adding web app fullscreen support as described in
http://stackoverflow.com/questions/7517352/fullscreen-web-app-for-android#24848302

Its only adding one line of html.

**Comment by JasonPuglisi** [comment]
I don't have any android devices, so let me know if this does/doesn't work. On a side note, I don't really like the way this looks on mobile, or at least on my iPhone. I should probably make it a bit more responsive.

**Comment by noooz** [comment]
There is a typo, but this way it works:
 meta(name='mobile-web-app-capable', content='yes') 

I like the way it looks on mobile. At least android. I use the app on an old mobile that I use only for this purpose.

**Comment by JasonPuglisi** [comment]
Ah, fixed that now. Glad to hear it. The problem I have is that the text sometimes overlaps on mobile. It's also impossible to toggle weather/extended info, so those are the main things I would want to fix.

**Comment by noooz** [comment]
Sorry, there is another typo: movile -> mobile
I don't use the weather thing. I think it's not working in my area (germany/freiburg)

**Comment by JasonPuglisi** [comment]
Man this is what happens when you try to work on multiple things at a time. I actually read it over this time, and I'm confident it's all typed correctly.

**Comment by noooz** [comment]
It's working now :) Thanks, I didn't expect it to have the results so quick :)

**Comment by hans-juergen** [comment]
Searching through the issues for "Android" found this thread, so I wonder if this added support means that it would also work on modern digital picture frames or LED screens? See this related new support thread:

https://support.last.fm/t/digital-picture-frame-or-led-screen-showing-currently-scrobbling/63572/

**Comment by JasonPuglisi** [comment]
I think it should work fine, but might not look perfect on small resolutions. It scales to most devices, but if a screen is significantly taller/wider in one dimension (like a phone), things may be squashed.
